const stateHash = {
  stateId2CodeMap: {
    0: "AR",
    1: "CA",
    2: "IL",
    3: "KS",
    4: "MS",
    5: "OH",
    6: "TX",
    7: "AL",
    8: "IA",
    9: "LA",
    10: "MN",
    11: "MO",
    12: "NE",
    13: "AZ",
    14: "CO",
    15: "IN",
    16: "MI",
    17: "MT",
    18: "NY",
    19: "OR",
    20: "VA",
    21: "WY",
    22: "NC",
    23: "OK",
    24: "TN",
    25: "WI",
    26: "AK",
    27: "VT",
    28: "ND",
    29: "GA",
    30: "ME",
    31: "RI",
    32: "WV",
    33: "ID",
    34: "SD",
    35: "NM",
    36: "WA",
    37: "PA",
    38: "FL",
    39: "UT",
    40: "KY",
    41: "NH",
    42: "SC",
    43: "NV",
    44: "HI",
    45: "NJ",
    46: "CT",
    47: "MD",
    48: "MA",
    49: "DE",
    50: "DC"
  },
  state_hash: {
    AL: "Alabama",
    AK: "Alaska",
    AZ: "Arizona",
    AR: "Arkansas",
    CA: "California",
    CO: "Colorado",
    CT: "Connecticut",
    DE: "Delaware",
    FL: "Florida",
    GA: "Georgia",
    HI: "Hawaii",
    ID: "Idaho",
    IL: "Illinois",
    IN: "Indiana",
    IA: "Iowa",
    KS: "Kansas",
    KY: "Kentucky",
    LA: "Louisiana",
    ME: "Maine",
    MD: "Maryland",
    MA: "Massachusetts",
    MI: "Michigan",
    MN: "Minnesota",
    MS: "Mississippi",
    MO: "Missouri",
    MT: "Montana",
    NE: "Nebraska",
    NV: "Nevada",
    NH: "New Hampshire",
    NJ: "New Jersey",
    NM: "New Mexico",
    NY: "New York",
    NC: "North Carolina",
    ND: "North Dakota",
    OH: "Ohio",
    OK: "Oklahoma",
    OR: "Oregon",
    PA: "Pennsylvania",
    RI: "Rhode Island",
    SC: "South Carolina",
    SD: "South Dakota",
    TN: "Tennessee",
    TX: "Texas",
    UT: "Utah",
    VT: "Vermont",
    VA: "Virginia",
    WA: "Washington",
    WV: "West Virginia",
    WI: "Wisconsin",
    WY: "Wyoming",
    DC: "Washington D.C."
  }
};

export default stateHash;
